# Request / Goal
geometry_msgs/PoseStamped goal_pose
float64 max_velocity_x
float64 max_velocity_y
float64 max_velocity_z
float64 max_yaw_rate
---
# Result
bool success
float64 elapsed_time    # seconds
---
# Feedback
geometry_msgs/PoseStamped goal_pose
float64 distance_remaining              # meters
float64 elapsed_time                    # seconds