bt_navigator:
  ros__parameters:
    use_sim_time: &default_use_sim_time False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /visual_slam/tracking/odometry
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: *default_use_sim_time

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: *default_use_sim_time

controller_server:
  ros__parameters:
    # TODO: enable when navigation2 supports twist stamped
    # enable_stamped_cmd_vel: True
    use_sim_time: *default_use_sim_time
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      max_vel_x: 0.5
      max_vel_y: 0.5
      max_vel_theta: 1.0
      max_speed_xy: 0.707
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]

local_costmap:
  local_costmap:
    ros__parameters:
      # footprint_padding: 0.03
      # update_frequency: 5.0
      # publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: *default_use_sim_time
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      robot_radius: 0.35
      # transform_tolerance: 0.3
      # footprint: "[ [0.14, 0.25], [0.14, -0.25], [-0.607, -0.25], [-0.607, 0.25] ]"
      # mark_threshold: 2
      always_send_full_costmap: True
      # plugins: ["voxel_layer", "inflation_layer"]
      plugins: ["nvblox_layer", "inflation_layer"]
      # voxel_layer:
      #   plugin: "nav2_costmap_2d::VoxelLayer"
      #   enabled: True
      #   publish_voxel_map: True
      #   observation_sources: scan
      #   scan:
      #     topic: /scan
      #     max_obstacle_height: 2.0
      #     clearing: True
      #     marking: True
      #     data_type: "LaserScan"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        cost_scaling_factor: 2.0
        inflation_radius: 1.0
      nvblox_layer:
        plugin: "nvblox::nav2::NvbloxCostmapLayer"
        enabled: True
        nav2_costmap_global_frame: odom # must match with global_frame of local_costmap
        nvblox_map_slice_topic: "/nvblox_node/pessimistic_static_map_slice"
        convert_to_binary_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      # footprint_padding: 0.0
      # update_frequency: 1.0
      # publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: *default_use_sim_time
      robot_radius: 0.35
      # footprint: "[ [0.14, 0.25], [0.14, -0.25], [-0.607, -0.25], [-0.607, 0.25] ]"
      resolution: 0.05
      lethal_cost_threshold: 50
      # # The following is only used as a default when no map is specified.
      width: 50
      height: 50
      origin_x: -25.0
      origin_y: -25.0
      track_unknown_space: False
      mark_threshold: 2
      always_send_full_costmap: True
      # plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      plugins: ["nvblox_layer", "inflation_layer"]
      # static_layer:
      #   plugin: "nav2_costmap_2d::StaticLayer"
      #   map_subscribe_transient_local: True
      #   enabled: true
      # obstacle_layer:
      #   plugin: "nav2_costmap_2d::ObstacleLayer"
      #   enabled: True
      #   observation_sources: scan
      #   scan:
      #     topic: /scan
      #     clearing: True
      #     marking: True
      #     data_type: "LaserScan"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        cost_scaling_factor: 5.0
        inflation_radius: 1.0
      nvblox_layer:
        plugin: "nvblox::nav2::NvbloxCostmapLayer"
        enabled: True
        nav2_costmap_global_frame: map # must match with global_frame of global_costmap
        nvblox_map_slice_topic: "/nvblox_node/static_map_slice"
        convert_to_binary_costmap: True

# map_server:
#   ros__parameters:
#     use_sim_time: True
#     # Overridden in launch by the "map" launch configuration or provided default value.
#     # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
#     yaml_filename: ""
# map_saver:
#   ros__parameters:
#     use_sim_time: True
#     save_map_timeout: 5.0
#     free_thresh_default: 0.25
#     occupied_thresh_default: 0.65
#     map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    # expected_planner_frequency: 1.0
    use_sim_time: *default_use_sim_time
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      # plugin: "nav2_smac_planner/SmacPlannerHybrid"
      # downsample_costmap: false # whether or not to downsample the map
      # downsampling_factor: 1 # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      # tolerance: 0.25 # dist-to-goal heuristic cost (distance) for valid tolerance endpoints if exact goal cannot be found.
      # allow_unknown: true # allow traveling in unknown space
      # max_iterations: 1000000 # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      # max_on_approach_iterations: 1000 # Maximum number of iterations after within tolerances to continue to try to find exact solution
      # max_planning_time: 5.0 # max time in s for planner to plan, smooth
      # motion_model_for_search: "REEDS_SHEPP" # Hybrid-A* Dubin, Redds-Shepp
      # angle_quantization_bins: 72 # Number of angle bins for search
      # analytic_expansion_ratio: 3.5 # The ratio to attempt analytic expansions during search for final approach.
      # analytic_expansion_max_length: 1.5 # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
      # minimum_turning_radius: 0.20 # minimum turning radius in m of path / vehicle
      # reverse_penalty: 2.0 # Penalty to apply if motion is reversing, must be => 1
      # change_penalty: 0.0 # Penalty to apply if motion is changing directions (L to R), must be >= 0
      # non_straight_penalty: 1.2 # Penalty to apply if motion is non-straight, must be => 1
      # cost_penalty: 3.0 # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      # retrospective_penalty: 0.015
      # lookup_table_size: 20.0 # Size of the dubin/reeds-sheep distance window to cache, in meters.
      # cache_obstacle_heuristic: false # Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      # debug_visualizations: false # For Hybrid nodes: Whether to publish expansions on the /expansions topic as an array of poses (the orientation has no meaning) and the path's footprints on the /planned_footprints topic. WARNING: heavy to compute and to display, for debug only as it degrades the performance.
      # use_quadratic_cost_penalty: False
      # downsample_obstacle_heuristic: True
      # allow_primitive_interpolation: False
      # smooth_path: True # If true, does a simple and quick smoothing post-processing to the path
      # smoother:
      #   max_iterations: 1000
      #   w_smooth: 0.3
      #   w_data: 0.2
      #   tolerance: 1.0e-10
      #   do_refinement: true
      #   refinement_num: 2

smoother_server:
  ros__parameters:
    use_sim_time: *default_use_sim_time
    smoother_plugins: ["simple_smoother"]
    enable_stamped_cmd_vel: True
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      # tolerance: 1.0e-10
      # max_its: 1000
      # do_refinement: True

behavior_server:
  ros__parameters:
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    use_sim_time: *default_use_sim_time
    enable_stamped_cmd_vel: True
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"

# robot_state_publisher:
#   ros__parameters:
#     use_sim_time: True
# waypoint_follower:
#   ros__parameters:
#     use_sim_time: True
#     loop_rate: 20
#     stop_on_failure: false
#     waypoint_task_executor_plugin: "wait_at_waypoint"
#     wait_at_waypoint:
#       plugin: "nav2_waypoint_follower::WaitAtWaypoint"
#       enabled: True
#       waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: *default_use_sim_time
    # smoothing_frequency: 20.0
    # scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.5, 1.0]
    min_velocity: [-0.5, -0.5, -1.0]
    # max_accel: [2.5, 0.0, 3.2]
    # max_decel: [-2.5, 0.0, -3.2]
    # odom_duration: 0.1
    # deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
